import * as act from "./actions"

const initialState = {
    games: [],
    cart: [],
    gameDetail: [],
    gameComingSoon: [
        {
            "id": 2390150,
            "type": 0,
            "name": "Supporter Pack 1",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 250,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2390150/capsule_616x353.jpg?t=1686782976",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2390150/capsule_184x69.jpg?t=1686782976",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2390150/header.jpg?t=1686782976"
            },
            {
            "id": 1306060,
            "type": 0,
            "name": "Golf Club Architect",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 300,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1306060/capsule_616x353.jpg?t=1685906496",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1306060/capsule_184x69.jpg?t=1685906496",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1306060/header.jpg?t=1685906496"
            },
            {
            "id": 1039280,
            "type": 0,
            "name": "ProtoCorgi",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 275,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1039280/capsule_616x353.jpg?t=1685707924",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1039280/capsule_184x69.jpg?t=1685707924",
            "windows_available": true,
            "mac_available": false,
            "linux_available": true,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1039280/header.jpg?t=1685707924",
            "controller_support": "full"
            },
            {
            "id": 1299540,
            "type": 0,
            "name": "The Zone: Stalker Stories",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 12,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1299540/capsule_616x353.jpg?t=1685748965",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1299540/capsule_184x69.jpg?t=1685748965",
            "windows_available": true,
            "mac_available": false,
            "linux_available": true,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1299540/header.jpg?t=1685748965"
            },
            {
            "id": 671860,
            "type": 0,
            "name": "BattleBit Remastered",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 0,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/671860/capsule_616x353.jpg?t=1686829253",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/671860/capsule_184x69.jpg?t=1686829253",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/671860/header.jpg?t=1686829253"
            },
            {
            "id": 2400200,
            "type": 0,
            "name": "StrangerZ Demo",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 0,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2400200/capsule_616x353.jpg?t=1686683984",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2400200/capsule_184x69.jpg?t=1686683984",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2400200/header.jpg?t=1686683984"
            },
            {
            "id": 2119760,
            "type": 0,
            "name": "SHIRIME 2: The Genesis of Butt-Eye  - Prologue",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 0,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2119760/capsule_616x353.jpg?t=1686813206",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2119760/capsule_184x69.jpg?t=1686813206",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2119760/header.jpg?t=1686813206"
            },
            {
            "id": 2428560,
            "type": 0,
            "name": "Druidwalker Soundtrack",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 120,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2428560/capsule_616x353.jpg?t=1686158954",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2428560/capsule_184x69.jpg?t=1686158954",
            "windows_available": true,
            "mac_available": true,
            "linux_available": true,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2428560/header.jpg?t=1686158954"
            },
            {
            "id": 2231060,
            "type": 0,
            "name": "Druidwalker",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 0,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2231060/capsule_616x353.jpg?t=1686832540",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2231060/capsule_184x69.jpg?t=1686832540",
            "windows_available": true,
            "mac_available": true,
            "linux_available": true,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2231060/header.jpg?t=1686832540"
            },
            {
            "id": 2343930,
            "type": 0,
            "name": "Eyes Of War",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 45,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2343930/capsule_616x353.jpg?t=1686824094",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2343930/capsule_184x69.jpg?t=1686824094",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2343930/header.jpg?t=1686824094"
        }
    ],
    gameOffer: [
        {
        "id": 2390150,
        "type": 0,
        "name": "Supporter Pack 1",
        "discounted": false,
        "discount_percent": 0,
        "original_price": null,
        "final_price": 20,
        "currency": "ARS",
        "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2390150/capsule_616x353.jpg?t=1686782976",
        "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2390150/capsule_184x69.jpg?t=1686782976",
        "windows_available": true,
        "mac_available": false,
        "linux_available": false,
        "streamingvideo_available": false,
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2390150/header.jpg?t=1686782976"
        },
        {
        "id": 1306060,
        "type": 0,
        "name": "Golf Club Architect",
        "discounted": false,
        "discount_percent": 0,
        "original_price": null,
        "final_price": 100,
        "currency": "ARS",
        "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1306060/capsule_616x353.jpg?t=1685906496",
        "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1306060/capsule_184x69.jpg?t=1685906496",
        "windows_available": true,
        "mac_available": false,
        "linux_available": false,
        "streamingvideo_available": false,
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1306060/header.jpg?t=1685906496"
        },
        {
        "id": 1039280,
        "type": 0,
        "name": "ProtoCorgi",
        "discounted": false,
        "discount_percent": 0,
        "original_price": null,
        "final_price": 0,
        "currency": "ARS",
        "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1039280/capsule_616x353.jpg?t=1685707924",
        "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1039280/capsule_184x69.jpg?t=1685707924",
        "windows_available": true,
        "mac_available": false,
        "linux_available": true,
        "streamingvideo_available": false,
        "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1039280/header.jpg?t=1685707924",
        "controller_support": "full"
}, {
    "id": 1593500,
    "type": 0,
    "name": "God of War",
    "discounted": true,
    "discount_percent": 40,
    "original_price": 849900,
    "final_price": 509940,
    "currency": "ARS",
    "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1593500/capsule_616x353.jpg?t=1650554420",
    "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1593500/capsule_184x69.jpg?t=1650554420",
    "windows_available": true,
    "mac_available": false,
    "linux_available": false,
    "streamingvideo_available": false,
    "discount_expiration": 1686848400,
    "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1593500/header.jpg?t=1650554420",
    "controller_support": "full"
    },
    {
    "id": 124923,
    "type": 1,
    "name": "The Witcher 3: Wild Hunt - Complete Edition",
    "discounted": true,
    "discount_percent": 70,
    "original_price": 329999,
    "final_price": 98999,
    "currency": "ARS",
    "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/subs/124923/capsule_616x353.jpg?t=1671055800",
    "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/subs/124923/capsule_184x69.jpg?t=1671055800",
    "windows_available": true,
    "mac_available": false,
    "linux_available": false,
    "streamingvideo_available": false,
    "discount_expiration": 1687107600,
    "header_image": "https://cdn.akamai.steamstatic.com/steam/subs/124923/header_ratio.jpg?t=1671055800",
    "controller_support": "full"
    },
    {
    "id": 1293830,
    "type": 0,
    "name": "Forza Horizon 4",
    "discounted": true,
    "discount_percent": 67,
    "original_price": 599900,
    "final_price": 197967,
    "currency": "ARS",
    "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1293830/capsule_616x353.jpg?t=1667326422",
    "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1293830/capsule_184x69.jpg?t=1667326422",
    "windows_available": true,
    "mac_available": false,
    "linux_available": false,
    "streamingvideo_available": false,
    "discount_expiration": 1686848400,
    "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1293830/header.jpg?t=1667326422",
    "controller_support": "full"
    },
    {
    "id": 413150,
    "type": 0,
    "name": "Stardew Valley",
    "discounted": true,
    "discount_percent": 20,
    "original_price": 17999,
    "final_price": 14399,
    "currency": "ARS",
    "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/413150/capsule_616x353.jpg?t=1666917466",
    "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/413150/capsule_184x69.jpg?t=1666917466",
    "windows_available": true,
    "mac_available": true,
    "linux_available": true,
    "streamingvideo_available": false,
    "discount_expiration": 1686848400,
    "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/413150/header.jpg?t=1666917466",
    "controller_support": "full"
    },
    {
    "id": 1182900,
    "type": 0,
    "name": "A Plague Tale: Requiem",
    "discounted": true,
    "discount_percent": 50,
    "original_price": 699900,
    "final_price": 349950,
    "currency": "ARS",
    "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1182900/capsule_616x353.jpg?t=1678973757",
    "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1182900/capsule_184x69.jpg?t=1678973757",
    "windows_available": true,
    "mac_available": false,
    "linux_available": false,
    "streamingvideo_available": false,
    "discount_expiration": 1687453200,
    "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1182900/header.jpg?t=1678973757",
    "controller_support": "full"
    },
    {
    "id": 275850,
    "type": 0,
    "name": "No Man's Sky",
    "discounted": true,
    "discount_percent": 50,
    "original_price": 380000,
    "final_price": 190000,
    "currency": "ARS",
    "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/275850/capsule_616x353_alt_assets_18.jpg?t=1686146204",
    "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/275850/capsule_184x69_alt_assets_18.jpg?t=1686146204",
    "windows_available": true,
    "mac_available": true,
    "linux_available": false,
    "streamingvideo_available": false,
    "discount_expiration": 1687194000,
    "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/275850/header_alt_assets_18.jpg?t=1686146204",
    "controller_support": "full"
    },
    {
    "id": 812140,
    "type": 0,
    "name": "Assassin's Creed® Odyssey",
    "discounted": true,
    "discount_percent": 80,
    "original_price": 599900,
    "final_price": 119980,
    "currency": "ARS",
    "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/812140/capsule_616x353.jpg?t=1670596226",
    "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/812140/capsule_184x69.jpg?t=1670596226",
    "windows_available": true,
    "mac_available": false,
    "linux_available": false,
    "streamingvideo_available": false,
    "discount_expiration": 1686848400,
    "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/812140/header.jpg?t=1670596226"
    }],
    gamesTopSellers: [
        {
            "id": 2396440,
            "type": 0,
            "name": "Call of Duty®: Modern Warfare® II - BlackCell (Temporada 4)",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 368900,
            "final_price": 368900,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2396440/capsule_616x353.jpg?t=1686758791",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2396440/capsule_184x69.jpg?t=1686758791",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2396440/header.jpg?t=1686758791",
            "controller_support": "full"
            },
            {
            "id": 671860,
            "type": 0,
            "name": "BattleBit Remastered",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 263000,
            "final_price": 263000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/671860/capsule_616x353.jpg?t=1686841355",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/671860/capsule_184x69.jpg?t=1686841355",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/671860/header.jpg?t=1686841355"
            },
            {
            "id": 1716740,
            "type": 0,
            "name": "STARFIELD",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 1199900,
            "final_price": 1199900,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1716740/capsule_616x353.jpg?t=1686617933",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1716740/capsule_184x69.jpg?t=1686617933",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1716740/header.jpg?t=1686617933",
            "controller_support": "full"
            },
            {
            "id": 1364780,
            "type": 0,
            "name": "Street Fighter™ 6",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 990000,
            "final_price": 990000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1364780/capsule_616x353.jpg?t=1686291121",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1364780/capsule_184x69.jpg?t=1686291121",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1364780/header.jpg?t=1686291121"
            },
            {
            "id": 1091500,
            "type": 0,
            "name": "Cyberpunk 2077",
            "discounted": true,
            "discount_percent": 50,
            "original_price": 999900,
            "final_price": 499950,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1091500/capsule_616x353.jpg?t=1686834071",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1091500/capsule_184x69.jpg?t=1686834071",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687107600,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg?t=1686834071"
            },
            {
            "id": 2108330,
            "type": 0,
            "name": "F1® 23",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 1199900,
            "final_price": 1199900,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2108330/capsule_616x353_alt_assets_0.jpg?t=1686590662",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2108330/capsule_184x69.jpg?t=1686590662",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2108330/header.jpg?t=1686590662",
            "controller_support": "full"
            },
            {
            "id": 2108330,
            "type": 0,
            "name": "F1® 23",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 1199900,
            "final_price": 1199900,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2108330/capsule_616x353_alt_assets_0.jpg?t=1686590662",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2108330/capsule_184x69.jpg?t=1686590662",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2108330/header.jpg?t=1686590662",
            "controller_support": "full"
            },
            {
            "id": 962130,
            "type": 0,
            "name": "Grounded",
            "discounted": true,
            "discount_percent": 40,
            "original_price": 399900,
            "final_price": 239940,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/962130/capsule_616x353.jpg?t=1684963474",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/962130/capsule_184x69.jpg?t=1684963474",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687194000,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/962130/header.jpg?t=1684963474",
            "controller_support": "full"
            },
            {
            "id": 5699,
            "type": 2,
            "name": "Grand Theft Auto V: Edición Premium",
            "discounted": true,
            "discount_percent": 63,
            "original_price": 759800,
            "final_price": 281508,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/bundles/5699/qipqf90z2z7h4x3i/capsule_616x353_latam.jpg?t=1678931390",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/bundles/5699/qipqf90z2z7h4x3i/capsule_184x69_latam.jpg?t=1678931390",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/bundles/5699/qipqf90z2z7h4x3i/header_ratio_latam.jpg?t=1678931390",
            "controller_support": "full"
            },
            {
            "id": 2138330,
            "type": 0,
            "name": "Cyberpunk 2077: Phantom Liberty",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 499900,
            "final_price": 499900,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2138330/capsule_616x353.jpg?t=1686829573",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2138330/capsule_184x69.jpg?t=1686829573",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2138330/header_alt_assets_0_latam.jpg?t=1686829573"
            }
    ],
    gamesNewReleases: [
        {
            "id": 1039280,
            "type": 0,
            "name": "ProtoCorgi",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 69900,
            "final_price": 69900,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1039280/capsule_616x353.jpg?t=1686840694",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1039280/capsule_184x69.jpg?t=1686840694",
            "windows_available": true,
            "mac_available": false,
            "linux_available": true,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1039280/header.jpg?t=1686840694",
            "controller_support": "full"
            },
            {
            "id": 1710540,
            "type": 0,
            "name": "Fall of Porcupine",
            "discounted": true,
            "discount_percent": 15,
            "original_price": 140000,
            "final_price": 119000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1710540/capsule_616x353_alt_assets_1.jpg?t=1686839436",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1710540/capsule_184x69_alt_assets_1.jpg?t=1686839436",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687453209,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1710540/header_alt_assets_1.jpg?t=1686839436",
            "controller_support": "full"
            },
            {
            "id": 2418000,
            "type": 0,
            "name": "Combat Mission: Red Thunder",
            "discounted": true,
            "discount_percent": 15,
            "original_price": 380000,
            "final_price": 323000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2418000/capsule_616x353.jpg?t=1686837624",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2418000/capsule_184x69.jpg?t=1686837624",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687453242,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2418000/header.jpg?t=1686837624"
            },
            {
            "id": 2442150,
            "type": 0,
            "name": "Heavy Metal Titans",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 105000,
            "final_price": 105000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2442150/capsule_616x353.jpg?t=1686836434",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2442150/capsule_184x69.jpg?t=1686836434",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2442150/header.jpg?t=1686836434"
            },
            {
            "id": 2360690,
            "type": 0,
            "name": "Pixel Ripped 1978",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 175000,
            "final_price": 175000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2360690/capsule_616x353.jpg?t=1686842138",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2360690/capsule_184x69.jpg?t=1686842138",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2360690/header.jpg?t=1686842138"
            },
            {
            "id": 2440730,
            "type": 0,
            "name": "Snoody: One of the Ayrie",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 0,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2440730/capsule_616x353.jpg?t=1686827796",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2440730/capsule_184x69.jpg?t=1686827796",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2440730/header.jpg?t=1686827796"
            },
            {
            "id": 2430620,
            "type": 0,
            "name": "Castle of Terror",
            "discounted": true,
            "discount_percent": 10,
            "original_price": 24900,
            "final_price": 22410,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2430620/capsule_616x353.jpg?t=1686820032",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2430620/capsule_184x69.jpg?t=1686820032",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687453210,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2430620/header.jpg?t=1686820032"
            },
            {
            "id": 2379680,
            "type": 0,
            "name": "云端派对",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 0,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2379680/capsule_616x353.jpg?t=1686817688",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2379680/capsule_184x69.jpg?t=1686817688",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2379680/header.jpg?t=1686817688"
            },
            {
            "id": 2444660,
            "type": 0,
            "name": "네개의 빛",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 140000,
            "final_price": 140000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2444660/capsule_616x353.jpg?t=1686812671",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2444660/capsule_184x69.jpg?t=1686812671",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2444660/header.jpg?t=1686812671"
            },
            {
            "id": 2417400,
            "type": 0,
            "name": "Defiled Survivors: Prologue",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 0,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2417400/capsule_616x353.jpg?t=1686806991",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2417400/capsule_184x69.jpg?t=1686806991",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2417400/header.jpg?t=1686806991"
            },
            {
            "id": 2436380,
            "type": 0,
            "name": "狐狸探險記 歸途",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 16500,
            "final_price": 16500,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2436380/capsule_616x353.jpg?t=1686804386",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2436380/capsule_184x69.jpg?t=1686804386",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2436380/header.jpg?t=1686804386"
            },
            {
            "id": 2071560,
            "type": 0,
            "name": "Modern Fantasy - Urban Legends",
            "discounted": true,
            "discount_percent": 50,
            "original_price": 12999,
            "final_price": 6499,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2071560/capsule_616x353.jpg?t=1686802884",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2071560/capsule_184x69.jpg?t=1686802884",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687359600,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2071560/header.jpg?t=1686802884"
            },
            {
            "id": 2305490,
            "type": 0,
            "name": "THE SEGMENT TWINS",
            "discounted": true,
            "discount_percent": 10,
            "original_price": 90000,
            "final_price": 81000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2305490/capsule_616x353.jpg?t=1686801617",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2305490/capsule_184x69.jpg?t=1686801617",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366814,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2305490/header.jpg?t=1686801617",
            "controller_support": "full"
            },
            {
            "id": 1398910,
            "type": 0,
            "name": "Jorel’s Brother and The Most Important Game of the Galaxy",
            "discounted": true,
            "discount_percent": 23,
            "original_price": 62000,
            "final_price": 47740,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1398910/capsule_616x353.jpg?t=1686831741",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1398910/capsule_184x69.jpg?t=1686831741",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366842,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1398910/header.jpg?t=1686831741",
            "controller_support": "full"
            },
            {
            "id": 2353450,
            "type": 0,
            "name": "少女战场",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 0,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2353450/capsule_616x353.jpg?t=1686798001",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2353450/capsule_184x69.jpg?t=1686798001",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2353450/header.jpg?t=1686798001"
            },
            {
            "id": 2380760,
            "type": 0,
            "name": "Lofi Milk Delivery",
            "discounted": true,
            "discount_percent": 10,
            "original_price": 40000,
            "final_price": 36000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2380760/capsule_616x353.jpg?t=1686782664",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2380760/capsule_184x69.jpg?t=1686782664",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366821,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2380760/header.jpg?t=1686782664"
            },
            {
            "id": 2433220,
            "type": 0,
            "name": "Reflector Rhythm Master",
            "discounted": true,
            "discount_percent": 15,
            "original_price": 32000,
            "final_price": 27200,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2433220/capsule_616x353.jpg?t=1686780029",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2433220/capsule_184x69.jpg?t=1686780029",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366827,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2433220/header.jpg?t=1686780029"
            },
            {
            "id": 2446710,
            "type": 0,
            "name": "Cyberside Picnic",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 8200,
            "final_price": 8200,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2446710/capsule_616x353.jpg?t=1686769123",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2446710/capsule_184x69.jpg?t=1686769123",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2446710/header.jpg?t=1686769123"
            },
            {
            "id": 2408120,
            "type": 0,
            "name": "Solar Showdown",
            "discounted": false,
            "discount_percent": 0,
            "original_price": null,
            "final_price": 0,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2408120/capsule_616x353.jpg?t=1686770190",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2408120/capsule_184x69.jpg?t=1686770190",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2408120/header.jpg?t=1686770190"
            },
            {
            "id": 1906020,
            "type": 0,
            "name": "Drums Rock",
            "discounted": true,
            "discount_percent": 20,
            "original_price": 149999,
            "final_price": 119999,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1906020/capsule_616x353_alt_assets_0.jpg?t=1686764761",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1906020/capsule_184x69_alt_assets_0.jpg?t=1686764761",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366857,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1906020/header_alt_assets_0.jpg?t=1686764761"
            },
            {
            "id": 1787480,
            "type": 0,
            "name": "Metro Simulator 2",
            "discounted": true,
            "discount_percent": 40,
            "original_price": 79900,
            "final_price": 47940,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1787480/capsule_616x353.jpg?t=1686760392",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1787480/capsule_184x69.jpg?t=1686760392",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687971600,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1787480/header.jpg?t=1686760392"
            },
            {
            "id": 1991980,
            "type": 0,
            "name": "Wizardry School: Escape Room",
            "discounted": true,
            "discount_percent": 15,
            "original_price": 149900,
            "final_price": 127415,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1991980/capsule_616x353.jpg?t=1686758438",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1991980/capsule_184x69.jpg?t=1686758438",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366836,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1991980/header.jpg?t=1686758438",
            "controller_support": "full"
            },
            {
            "id": 2453520,
            "type": 0,
            "name": "Idle: Generators",
            "discounted": true,
            "discount_percent": 20,
            "original_price": 40000,
            "final_price": 32000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2453520/capsule_616x353.jpg?t=1686758411",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2453520/capsule_184x69.jpg?t=1686758411",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366810,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2453520/header.jpg?t=1686758411"
            },
            {
            "id": 1628260,
            "type": 0,
            "name": "Sinful Catalyst CH1: Ethereal Camellia",
            "discounted": false,
            "discount_percent": 0,
            "original_price": 16500,
            "final_price": 16500,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1628260/capsule_616x353.jpg?t=1686758380",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1628260/capsule_184x69.jpg?t=1686758380",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1628260/header.jpg?t=1686758380"
            },
            {
            "id": 2057120,
            "type": 0,
            "name": "Cabin Rush",
            "discounted": true,
            "discount_percent": 40,
            "original_price": 90000,
            "final_price": 54000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2057120/capsule_616x353.jpg?t=1686758144",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2057120/capsule_184x69.jpg?t=1686758144",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366841,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2057120/header.jpg?t=1686758144"
            },
            {
            "id": 1542110,
            "type": 0,
            "name": "Daydream: Forgotten Sorrow",
            "discounted": true,
            "discount_percent": 10,
            "original_price": 140000,
            "final_price": 126000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1542110/capsule_616x353.jpg?t=1686753631",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1542110/capsule_184x69.jpg?t=1686753631",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366831,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1542110/header.jpg?t=1686753631",
            "controller_support": "full"
            },
            {
            "id": 1217050,
            "type": 0,
            "name": "Shaolin vs Wutang 2",
            "discounted": true,
            "discount_percent": 15,
            "original_price": 19999,
            "final_price": 16999,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1217050/capsule_616x353.jpg?t=1686750720",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1217050/capsule_184x69.jpg?t=1686750720",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366857,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1217050/header.jpg?t=1686750720",
            "controller_support": "full"
            },
            {
            "id": 2396530,
            "type": 0,
            "name": "Brainroll",
            "discounted": true,
            "discount_percent": 10,
            "original_price": 24900,
            "final_price": 22410,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2396530/capsule_616x353.jpg?t=1686748024",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2396530/capsule_184x69.jpg?t=1686748024",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366802,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2396530/header.jpg?t=1686748024"
            },
            {
            "id": 2402100,
            "type": 0,
            "name": "Cube Airport - Puzzle",
            "discounted": true,
            "discount_percent": 40,
            "original_price": 24900,
            "final_price": 14940,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2402100/capsule_616x353.jpg?t=1686747823",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/2402100/capsule_184x69.jpg?t=1686747823",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366840,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/2402100/header.jpg?t=1686747823",
            "controller_support": "full"
            },
            {
            "id": 1309990,
            "type": 0,
            "name": "Creature Lab",
            "discounted": true,
            "discount_percent": 10,
            "original_price": 240000,
            "final_price": 216000,
            "currency": "ARS",
            "large_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1309990/capsule_616x353.jpg?t=1686748706",
            "small_capsule_image": "https://cdn.akamai.steamstatic.com/steam/apps/1309990/capsule_184x69.jpg?t=1686748706",
            "windows_available": true,
            "mac_available": false,
            "linux_available": false,
            "streamingvideo_available": false,
            "discount_expiration": 1687366805,
            "header_image": "https://cdn.akamai.steamstatic.com/steam/apps/1309990/header.jpg?t=1686748706",
            "controller_support": "full"
            }
    ]
};

const rootReducer=(state = initialState, action) => {
    switch(action.type) {

        case act.GET_GAMES:
            return {
                ...state,
                games: action.payload
            }

        case act.GET_DETAIL:
            return {
                ...state,
                gameDetail: action.payload
            }

        case act.GET_GAMES_OFFER:
            return {
                ...state,
                gameOffer: action.payload
            }

        case act.GET_GAMES_COMING_SOON:
            return {
                ...state,
                gameComingSoon: action.payload
            }
        
        case act.GET_GAMES_NEW_RELEASES:
            return {
                ...state,
                gamesNewReleases: action.payload
            }

        case act.GET_GAMES_TOP_SELLERS:
            return {
                ...state,
                gamesTopSellers: action.payload
            }

        case act.CLEAR_DETAIL:
            return {
                ...state,
                gameDetail: null
            }

        //?casos del carrito de compra
        case act.ADD_TO_CART:
            console.log(action.payload);
            return {
                ...state,
                cart: [...state.cart, ...action.payload]
            }

        case act.REMOVE_TO_CART:
            return {
                ...state,
                cart: state.cart.filter((game) => game.id !== action.payload )
            }

        case act.REMOVE_ALL_TO_CART:

        case act.CLEAR_CART:
            return {
                ...state,
                cart: []
            }

        

        default:
            return {...state};
    }
};

export default rootReducer;